In [33]:
#Importing Packages
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

#setting location for CSV files to be replaced with Amazon AWS connection 
fp_1 = 'calendar.csv'
fp_2 = 'listings.csv'
fp_3 = 'reviews.csv'

#reading CSV files into DF
cal_df = pd.read_csv(fp_1)
list_df = pd.read_csv(fp_2)
rev_df = pd.read_csv(fp_3)

In [6]:
# reviewing calendar df
cal_df.head()

   listing_id        date available   price
0      241032  2016-01-04         t  $85.00
1      241032  2016-01-05         t  $85.00
2      241032  2016-01-06         f     NaN
3      241032  2016-01-07         f     NaN
4      241032  2016-01-08         f     NaN

In [7]:
#reviewing listings dataframe
list_df.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,241032,https://www.airbnb.com/rooms/241032,20160104002432,2016-01-04,Stylish Queen Anne Apartment,NaN,Make your self at home in this charming one-be...,Make your self at home in this charming one-be...,none,NaN,...,10.0,f,NaN,WASHINGTON,f,moderate,f,f,2,4.07
1,953595,https://www.airbnb.com/rooms/953595,20160104002432,2016-01-04,Bright & Airy Queen Anne Apartment,Chemically sensitive? We've removed the irrita...,"Beautiful, hypoallergenic apartment in an extr...",Chemically sensitive? We've removed the irrita...,none,"Queen Anne is a wonderful, truly functional vi...",...,10.0,f,NaN,WASHINGTON,f,strict,t,t,6,1.48
2,3308979,https://www.airbnb.com/rooms/3308979,20160104002432,2016-01-04,New Modern House-Amazing water view,New modern house built in 2013. Spectacular s...,"Our house is modern, light and fresh with a wa...",New modern house built in 2013. Spectacular s...,none,Upper Queen Anne is a charming neighborhood fu...,...,10.0,f,NaN,WASHINGTON,f,strict,f,f,2,1.15
3,7421966,https://www.airbnb.com/rooms/7421966,20160104002432,2016-01-04,Queen Anne Chateau,A charming apartment that sits atop Queen Anne...,NaN,A charming apartment that sits atop Queen Anne...,none,NaN,...,NaN,f,NaN,WASHINGTON,f,flexible,f,f,1,NaN
4,278830,https://www.airbnb.com/rooms/278830,20160104002432,2016-01-04,Charming craftsman 3 bdm house,Cozy family craftman house in beautiful neighb...,Cozy family craftman house in beautiful neighb...,Cozy family craftman house in beautiful neighb...,none,We are in the beautiful neighborhood of Queen ...,...,9.0,f,NaN,WASHINGTON,f,strict,f,f,1,0.89

In [9]:
#reviewing reviews dataframe
rev_df.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,7202016,38917982,2015-07-19,28943674,Bianca,Cute and cozy place. Perfect location to every...
1,7202016,39087409,2015-07-20,32440555,Frank,Kelly has a great room in a very central locat...
2,7202016,39820030,2015-07-26,37722850,Ian,"Very spacious apartment, and in a great neighb..."
3,7202016,40813543,2015-08-02,33671805,George,Close to Seattle Center and all it has to offe...
4,7202016,41986501,2015-08-10,34959538,Ming,Kelly was a great host and very accommodating ...

In [11]:
#checking count for NAs
list_df.count()

id                                  3818
listing_url                         3818
scrape_id                           3818
last_scraped                        3818
name                                3818
                                    ...
cancellation_policy                 3818
require_guest_profile_picture       3818
require_guest_phone_verification    3818
calculated_host_listings_count      3818
reviews_per_month                   3191
Length: 92, dtype: int64

In [66]:
#creates ML Dataframe inclusive of review info
ml_df = list_df[["reviews_per_month","require_guest_phone_verification","require_guest_profile_picture","cancellation_policy","instant_bookable","requires_license","review_scores_value","review_scores_location","review_scores_communication","review_scores_checkin","review_scores_cleanliness","review_scores_accuracy","review_scores_rating","number_of_reviews","availability_365","availability_90","availability_60","availability_30","maximum_nights","minimum_nights","extra_people","guests_included","price","bed_type","beds","bedrooms","bathrooms","accommodates","room_type","property_type","neighbourhood_group_cleansed","host_identity_verified","host_has_profile_pic","host_is_superhost","host_acceptance_rate","host_response_rate","host_response_time"]].copy()

# counting df
ml_df.head()

,reviews_per_month,require_guest_phone_verification,require_guest_profile_picture,cancellation_policy,instant_bookable,requires_license,review_scores_value,review_scores_location,review_scores_communication,review_scores_checkin,...,accommodates,room_type,property_type,neighbourhood_group_cleansed,host_identity_verified,host_has_profile_pic,host_is_superhost,host_acceptance_rate,host_response_rate,host_response_time
0,4.07,f,f,moderate,f,f,10.0,9.0,10.0,10.0,...,4,Entire home/apt,Apartment,Queen Anne,t,t,f,100%,96%,within a few hours
1,1.48,t,t,strict,f,f,10.0,10.0,10.0,10.0,...,4,Entire home/apt,Apartment,Queen Anne,t,t,t,100%,98%,within an hour
2,1.15,f,f,strict,f,f,10.0,10.0,10.0,10.0,...,11,Entire home/apt,House,Queen Anne,t,t,f,100%,67%,within a few hours
3,NaN,f,f,flexible,f,f,NaN,NaN,NaN,NaN,...,3,Entire home/apt,Apartment,Queen Anne,t,t,f,NaN,NaN,NaN
4,0.89,f,f,strict,f,f,9.0,9.0,10.0,10.0,...,6,Entire home/apt,House,Queen Anne,t,t,f,NaN,100%,within an hour

In [67]:
#droping NAs in machine learning dataframe
ml_df = ml_df.dropna()
ml_df.count()

reviews_per_month                   2655
require_guest_phone_verification    2655
require_guest_profile_picture       2655
cancellation_policy                 2655
instant_bookable                    2655
requires_license                    2655
review_scores_value                 2655
review_scores_location              2655
review_scores_communication         2655
review_scores_checkin               2655
review_scores_cleanliness           2655
review_scores_accuracy              2655
review_scores_rating                2655
number_of_reviews                   2655
availability_365                    2655
availability_90                     2655
availability_60                     2655
availability_30                     2655
maximum_nights                      2655
minimum_nights                      2655
extra_people                        2655
guests_included                     2655
price                               2655
bed_type                            2655
beds                                2655
bedrooms                            2655
bathrooms                           2655
accommodates                        2655
room_type                           2655
property_type                       2655
neighbourhood_group_cleansed        2655
host_identity_verified              2655
host_has_profile_pic                2655
host_is_superhost                   2655
host_acceptance_rate                2655
host_response_rate                  2655
host_response_time                  2655
dtype: int64

In [71]:
#defining a good or a bad rating 
ml_df['rating_good_or_bad'] = np.where(ml_df['review_scores_value'] > 8, 'good_review', 'bad_review')

#checking good vs. bad rating count
good_bad_review_count = ml_df.groupby('rating_good_or_bad')['reviews_per_month'].count()
good_bad_review_count

rating_good_or_bad
bad_review      190
good_review    2465
Name: reviews_per_month, dtype: int64

In [91]:
#removing rating info to avoid skewing ML model 
ml_final = ml_df[["rating_good_or_bad","require_guest_phone_verification","require_guest_profile_picture","cancellation_policy","instant_bookable","requires_license","availability_365","availability_90","availability_60","availability_30","maximum_nights","minimum_nights","extra_people","guests_included","price","bed_type","beds","bedrooms","bathrooms","accommodates","room_type","property_type","neighbourhood_group_cleansed","host_identity_verified","host_has_profile_pic","host_is_superhost","host_acceptance_rate","host_response_rate","host_response_time"]].copy()

In [92]:
#encoding for all true and false variables: 

##encoding for superhost

# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# passing bridge-types-cat column (label encoded values of bridge_types)
enc_df = pd.DataFrame(enc.fit_transform(ml_final[['host_is_superhost']]).toarray())
# merge with main df bridge_df on key values
ml_final= ml_final.join(enc_df)
ml_final.rename(columns = {0:'not_a_superhost', 1:'a_superhost'}, inplace = True)
ml_final.head()

,rating_good_or_bad,require_guest_phone_verification,require_guest_profile_picture,cancellation_policy,instant_bookable,requires_license,availability_365,availability_90,availability_60,availability_30,...,property_type,neighbourhood_group_cleansed,host_identity_verified,host_has_profile_pic,host_is_superhost,host_acceptance_rate,host_response_rate,host_response_time,not_a_superhost,a_superhost
0,good_review,f,f,moderate,f,f,346,71,41,14,...,Apartment,Queen Anne,t,t,f,100%,96%,within a few hours,1.0,0.0
1,good_review,t,t,strict,f,f,291,16,13,13,...,Apartment,Queen Anne,t,t,t,100%,98%,within an hour,0.0,1.0
2,good_review,f,f,strict,f,f,220,17,6,1,...,House,Queen Anne,t,t,f,100%,67%,within a few hours,1.0,0.0
6,good_review,f,f,moderate,f,f,346,71,49,20,...,House,Queen Anne,t,t,t,100%,100%,within an hour,0.0,1.0
7,good_review,t,t,strict,f,f,100,42,42,22,...,Cabin,Queen Anne,t,t,t,100%,100%,within an hour,1.0,0.0

In [94]:
##encoding for host has profile pic

# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# passing bridge-types-cat column (label encoded values of bridge_types)
enc_df = pd.DataFrame(enc.fit_transform(ml_final[['host_has_profile_pic']]).toarray())
# merge with main df bridge_df on key values
ml_final= ml_final.join(enc_df)
ml_final.rename(columns = {0:'host_does_not_have_profile_pic', 1:'host_does_have_profile_pic'}, inplace = True)
ml_final.head()

,rating_good_or_bad,require_guest_phone_verification,require_guest_profile_picture,cancellation_policy,instant_bookable,requires_license,availability_365,availability_90,availability_60,availability_30,...,host_is_superhost,host_acceptance_rate,host_response_rate,host_response_time,not_a_superhost,a_superhost,has_profile_pic,does_not_have_profile_pic,host_does_not_have_profile_pic,host_does_have_profile_pic
0,good_review,f,f,moderate,f,f,346,71,41,14,...,f,100%,96%,within a few hours,1.0,0.0,0.0,1.0,0.0,1.0
1,good_review,t,t,strict,f,f,291,16,13,13,...,t,100%,98%,within an hour,0.0,1.0,0.0,1.0,0.0,1.0
2,good_review,f,f,strict,f,f,220,17,6,1,...,f,100%,67%,within a few hours,1.0,0.0,0.0,1.0,0.0,1.0
6,good_review,f,f,moderate,f,f,346,71,49,20,...,t,100%,100%,within an hour,0.0,1.0,0.0,1.0,0.0,1.0
7,good_review,t,t,strict,f,f,100,42,42,22,...,t,100%,100%,within an hour,1.0,0.0,0.0,1.0,0.0,1.0