In [173]:
#Importing Packages
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
import psycopg2
import sys
import boto3
import os
from config import config_database, config_password

##passowrd from config file 
pww = config_password

## AWS Database connection
conn = psycopg2.connect(database= "final-project",
                        host="final-project.cuwr3km7ozpl.us-east-1.rds.amazonaws.com",
                        user= "postgres",
                        password=pww ,
                        port="5432")

In [174]:
## Creates Unit Dataframe: 

cur = conn.cursor()
cur.execute("SELECT * FROM unit")

tuples_list = cur.fetchall()
cur.close()
column_names_unit = ["id","host_id","booking_id","name","neighbourhood_group","city","state","zipcode","latitude","longitude","property_type","room_type","accommodates",
"bathrooms","bedrooms","beds","bed_type","instant_bookable","cancellation_policy","require_guest_profile_picture","require_guest_phone_verification","number_of_reviews","first_review",
"last_review","review_scores_rating","review_scores_accuracy","review_scores_cleanliness",
"review_scores_checkin","review_scores_communication","review_scores_location","review_scores_value","reviews_per_month"]

unit = pd.DataFrame(tuples_list, columns=column_names_unit)
unit.head()

,id,host_id,booking_id,name,neighbourhood_group,city,state,zipcode,latitude,longitude,...,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,68508,340192,1130,"Olympics, LakeUnion, Downtown....",Cascade,Seattle,WA,98102.0,47.6366744,-122.323155,...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1,3697351,18835179,1214,5 Blocks from Pike Place Market,Downtown,Seattle,WA,98121.0,47.61381379,-122.3425287,...,2014-07-28,2015-12-06,87.0,9.0,7.0,10.0,10.0,10.0,9.0,6.16
2,5538874,10590193,2406,Nice Cozy Futon in Mapleleaf,Northgate,Seattle,WA,98125.0,47.70438255,-122.3221015,...,2015-05-28,2015-09-12,100.0,10.0,10.0,10.0,10.0,10.0,10.0,0.41
3,7462439,6678025,587,"Capitol Hill Apt, Magnificent Views",Central Area,Seattle,WA,98122.0,47.61780091,-122.3000238,...,2015-07-26,2015-07-26,80.0,10.0,10.0,10.0,10.0,10.0,8.0,0.18
4,14386,39377,541,Quiet Cozy Upstairs BR Green Lake,Other neighborhoods,Seattle,WA,98103.0,47.68724568,-122.3346957,...,2010-08-09,2015-11-25,96.0,10.0,9.0,10.0,10.0,10.0,10.0,0.46

In [175]:
## Creates Host Dataframe: 

cur = conn.cursor()

cur.execute("SELECT * FROM host")

tuples_list = cur.fetchall()
cur.close()
column_names_host = ["host_id","host_name","host_since","host_listings_count","host_location","host_response_time","host_response_rate",
"host_acceptance_rate","host_is_superhost","host_has_profile_pic","host_identity_verified"]

host = pd.DataFrame(tuples_list, columns=column_names_host)
host.head()

,host_id,host_name,host_since,host_listings_count,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_has_profile_pic,host_identity_verified
0,4193,Jessica,2008-11-10,4.0,"Seattle, Washington, United States",within a few hours,0.88,1.0,False,True,True
1,6207,Cory & Amanda,2009-01-08,1.0,"Seattle, Washington, United States",within an hour,1,1.0,True,True,True
2,8021,Becky,2009-02-16,4.0,"Boston, Massachusetts, United States",within a few hours,0.75,1.0,False,True,True
3,8993,Maddy,2009-03-03,1.0,"Seattle, Washington, United States",within an hour,1,1.0,False,True,True
4,11775,Andrew,2009-03-30,1.0,"Seattle, Washington, United States",within a few hours,1,1.0,False,True,True

In [176]:
#Checks Unit Table: 

unit_rows = len(unit.axes [0])

unit_cols = len(unit.axes[1])

print(unit)
print("Number of Rows: ", unit_rows)
print("Number of Columns: ", unit_cols)

            id   host_id  booking_id                                 name  \
0        68508    340192        1130    Olympics, LakeUnion, Downtown....
1      3697351  18835179        1214      5 Blocks from Pike Place Market
2      5538874  10590193        2406         Nice Cozy Futon in Mapleleaf
3      7462439   6678025         587  Capitol Hill Apt, Magnificent Views
4        14386     39377         541    Quiet Cozy Upstairs BR Green Lake
...        ...       ...         ...                                  ...
3813  10252110  36706828        1906    Spacious 4 Bed West Seattle House
3814  10265391  10607280         317  Art filled, quiet, walkable Seattle
3815  10292753   4874276        1225  Belltown 1brm 98 Walk Score Parking
3816  10334184  53065829        2894    Historic Capitol Hill Garden Apt.
3817  10339144  53208610        2956  Studio in the heart of Capitol Hill

      neighbourhood_group     city state  zipcode     latitude     longitude  \
0                 Cascade  Seattle    WA  98102.0   47.6366744   -122.323155
1                Downtown  Seattle    WA  98121.0  47.61381379  -122.3425287
2               Northgate  Seattle    WA  98125.0  47.70438255  -122.3221015
3            Central Area  Seattle    WA  98122.0  47.61780091  -122.3000238
4     Other neighborhoods  Seattle    WA  98103.0  47.68724568  -122.3346957
...                   ...      ...   ...      ...          ...           ...
3813         West Seattle  Seattle    WA  98116.0  47.56494994  -122.3979769
3814  Other neighborhoods  Seattle    WA  98103.0  47.66150339   -122.334257
3815             Downtown  Seattle    WA  98121.0  47.61483648  -122.3468338
3816         Capitol Hill  Seattle    WA  98102.0  47.62650039  -122.3198514
3817         Capitol Hill  Seattle    WA  98112.0  47.61926924  -122.3131715

      ... first_review last_review  review_scores_rating  \
0     ...         None        None                   NaN
1     ...   2014-07-28  2015-12-06                  87.0
2     ...   2015-05-28  2015-09-12                 100.0
3     ...   2015-07-26  2015-07-26                  80.0
4     ...   2010-08-09  2015-11-25                  96.0
...   ...          ...         ...                   ...
3813  ...         None        None                   NaN
3814  ...         None        None                   NaN
3815  ...         None        None                   NaN
3816  ...         None        None                   NaN
3817  ...         None        None                   NaN

     review_scores_accuracy  review_scores_cleanliness  review_scores_checkin  \
0                       NaN                        NaN                    NaN
1                       9.0                        7.0                   10.0
2                      10.0                       10.0                   10.0
3                      10.0                       10.0                   10.0
4                      10.0                        9.0                   10.0
...                     ...                        ...                    ...
3813                    NaN                        NaN                    NaN
3814                    NaN                        NaN                    NaN
3815                    NaN                        NaN                    NaN
3816                    NaN                        NaN                    NaN
3817                    NaN                        NaN                    NaN

     review_scores_communication  review_scores_location review_scores_value  \
0                            NaN                     NaN                 NaN
1                           10.0                    10.0                 9.0
2                           10.0                    10.0                10.0
3                           10.0                    10.0                 8.0
4                           10.0                    10.0                10.0
...                          ...                     ...                 ...
3813                         NaN                     NaN                 NaN
3814                         NaN                     NaN                 NaN
3815                         NaN                     NaN                 NaN
3816                         NaN                     NaN                 NaN
3817                         NaN                     NaN                 NaN

      reviews_per_month
0                  None
1                  6.16
2                  0.41
3                  0.18
4                  0.46
...                 ...
3813               None
3814               None
3815               None
3816               None
3817               None

[3818 rows x 32 columns]
Number of Rows:  3818
Number of Columns:  32

In [177]:
#Checks host table

host_rows = len(host.axes [0])

host_cols = len(host.axes[1])

print(host)
print("Number of Rows: ", host_rows)
print("Number of Columns: ", host_cols)

       host_id      host_name  host_since  host_listings_count  \
0         4193        Jessica  2008-11-10                  4.0
1         6207  Cory & Amanda  2009-01-08                  1.0
2         8021          Becky  2009-02-16                  4.0
3         8993          Maddy  2009-03-03                  1.0
4        11775         Andrew  2009-03-30                  1.0
...        ...            ...         ...                  ...
2746  52990042        Richard  2016-01-01                  1.0
2747  53050379            Ana  2016-01-02                  1.0
2748  53065829        Gabriel  2016-01-02                  1.0
2749  53169216           Judy  2016-01-03                  1.0
2750  53208610          Julie  2016-01-03                  2.0

                             host_location  host_response_time  \
0       Seattle, Washington, United States  within a few hours
1       Seattle, Washington, United States      within an hour
2     Boston, Massachusetts, United States  within a few hours
3       Seattle, Washington, United States      within an hour
4       Seattle, Washington, United States  within a few hours
...                                    ...                 ...
2746                                    US                 N/A
2747    Seattle, Washington, United States                 N/A
2748    Seattle, Washington, United States                 N/A
2749                                    US                 N/A
2750                                    US                 N/A

     host_response_rate  host_acceptance_rate host_is_superhost  \
0                  0.88                   1.0             False
1                     1                   1.0              True
2                  0.75                   1.0             False
3                     1                   1.0             False
4                     1                   1.0             False
...                 ...                   ...               ...
2746               None                   NaN             False
2747               None                   NaN             False
2748               None                   NaN             False
2749               None                   NaN             False
2750               None                   NaN             False

     host_has_profile_pic host_identity_verified
0                    True                   True
1                    True                   True
2                    True                   True
3                    True                   True
4                    True                   True
...                   ...                    ...
2746                 True                   True
2747                 True                  False
2748                 True                  False
2749                 True                  False
2750                 True                  False

[2751 rows x 11 columns]
Number of Rows:  2751
Number of Columns:  11

In [178]:
#merges both tables and checks output
#creates "ml_df"

ml_df = unit.merge(host, how = 'outer', on='host_id')

ml_df_rows = len(ml_df.axes [0])
ml_df_cols = len(ml_df.axes[1])

print(ml_df)
print("Number of Rows: ", ml_df_rows)
print("Number of Columns: ", ml_df_cols)

            id   host_id  booking_id                                 name  \
0        68508    340192        1130    Olympics, LakeUnion, Downtown....
1      8257837    340192        2633  In-City PH 180Ã‚Âº Unobstructed Views
2      3697351  18835179        1214      5 Blocks from Pike Place Market
3      5538874  10590193        2406         Nice Cozy Futon in Mapleleaf
4      2071305  10590193        2420   Nice Mapleleaf Single Private Room
...        ...       ...         ...                                  ...
3813  10250735  29543440        2594  Micro Studio in Lovely Capital Hill
3814  10252110  36706828        1906    Spacious 4 Bed West Seattle House
3815  10265391  10607280         317  Art filled, quiet, walkable Seattle
3816  10334184  53065829        2894    Historic Capitol Hill Garden Apt.
3817  10339144  53208610        2956  Studio in the heart of Capitol Hill

      neighbourhood_group     city state  zipcode     latitude     longitude  \
0                 Cascade  Seattle    WA  98102.0   47.6366744   -122.323155
1            Capitol Hill  Seattle    WA  98102.0  47.63698256  -122.3217332
2                Downtown  Seattle    WA  98121.0  47.61381379  -122.3425287
3               Northgate  Seattle    WA  98125.0  47.70438255  -122.3221015
4               Northgate  Seattle    WA  98125.0  47.70437884  -122.3208569
...                   ...      ...   ...      ...          ...           ...
3813         Capitol Hill  Seattle    WA  98102.0  47.62379136  -122.3165141
3814         West Seattle  Seattle    WA  98116.0  47.56494994  -122.3979769
3815  Other neighborhoods  Seattle    WA  98103.0  47.66150339   -122.334257
3816         Capitol Hill  Seattle    WA  98102.0  47.62650039  -122.3198514
3817         Capitol Hill  Seattle    WA  98112.0  47.61926924  -122.3131715

      ... host_name  host_since  host_listings_count  \
0     ...    Angela  2011-01-08                  2.0
1     ...    Angela  2011-01-08                  2.0
2     ...     Jakub  2014-07-24                  1.0
3     ...    Cheryl  2013-12-12                  2.0
4     ...    Cheryl  2013-12-12                  2.0
...   ...       ...         ...                  ...
3813  ...     Tyler  2015-03-18                  1.0
3814  ...     Julia  2015-06-25                  1.0
3815  ...       Jay  2013-12-13                  1.0
3816  ...   Gabriel  2016-01-02                  1.0
3817  ...     Julie  2016-01-03                  2.0

                           host_location  host_response_time  \
0     Seattle, Washington, United States  within a few hours
1     Seattle, Washington, United States  within a few hours
2     Seattle, Washington, United States        within a day
3     Seattle, Washington, United States      within an hour
4     Seattle, Washington, United States      within an hour
...                                  ...                 ...
3813     Portland, Oregon, United States        within a day
3814  Seattle, Washington, United States                 N/A
3815  Seattle, Washington, United States      within an hour
3816  Seattle, Washington, United States                 N/A
3817                                  US                 N/A

      host_response_rate host_acceptance_rate  host_is_superhost  \
0                      1                  1.0              False
1                      1                  1.0              False
2                    0.7                  1.0              False
3                      1                  1.0               True
4                      1                  1.0               True
...                  ...                  ...                ...
3813                 0.5                  1.0              False
3814                None                  NaN              False
3815                   1                  1.0              False
3816                None                  NaN              False
3817                None                  NaN              False

     host_has_profile_pic  host_identity_verified
0                    True                   False
1                    True                   False
2                    True                   False
3                    True                    True
4                    True                    True
...                   ...                     ...
3813                 True                   False
3814                 True                   False
3815                 True                    True
3816                 True                   False
3817                 True                   False

[3818 rows x 42 columns]
Number of Rows:  3818
Number of Columns:  42

In [179]:
#reviewing rml_df dataframe

ml_df.head()

,id,host_id,booking_id,name,neighbourhood_group,city,state,zipcode,latitude,longitude,...,host_name,host_since,host_listings_count,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_has_profile_pic,host_identity_verified
0,68508,340192,1130,"Olympics, LakeUnion, Downtown....",Cascade,Seattle,WA,98102.0,47.6366744,-122.323155,...,Angela,2011-01-08,2.0,"Seattle, Washington, United States",within a few hours,1,1.0,False,True,False
1,8257837,340192,2633,In-City PH 180Ã‚Âº Unobstructed Views,Capitol Hill,Seattle,WA,98102.0,47.63698256,-122.3217332,...,Angela,2011-01-08,2.0,"Seattle, Washington, United States",within a few hours,1,1.0,False,True,False
2,3697351,18835179,1214,5 Blocks from Pike Place Market,Downtown,Seattle,WA,98121.0,47.61381379,-122.3425287,...,Jakub,2014-07-24,1.0,"Seattle, Washington, United States",within a day,0.7,1.0,False,True,False
3,5538874,10590193,2406,Nice Cozy Futon in Mapleleaf,Northgate,Seattle,WA,98125.0,47.70438255,-122.3221015,...,Cheryl,2013-12-12,2.0,"Seattle, Washington, United States",within an hour,1,1.0,True,True,True
4,2071305,10590193,2420,Nice Mapleleaf Single Private Room,Northgate,Seattle,WA,98125.0,47.70437884,-122.3208569,...,Cheryl,2013-12-12,2.0,"Seattle, Washington, United States",within an hour,1,1.0,True,True,True

In [180]:
#checking count for NAs
ml_df.count()

id                                  3818
host_id                             3818
booking_id                          3818
name                                3818
neighbourhood_group                 3818
city                                3818
state                               3818
zipcode                             3811
latitude                            3818
longitude                           3818
property_type                       3817
room_type                           3818
accommodates                        3818
bathrooms                           3802
bedrooms                            3812
beds                                3817
bed_type                            3818
instant_bookable                    3818
cancellation_policy                 3818
require_guest_profile_picture       3818
require_guest_phone_verification    3818
number_of_reviews                   3818
first_review                        3191
last_review                         3191
review_scores_rating                3171
review_scores_accuracy              3160
review_scores_cleanliness           3165
review_scores_checkin               3160
review_scores_communication         3167
review_scores_location              3163
review_scores_value                 3162
reviews_per_month                   3191
host_name                           3816
host_since                          3816
host_listings_count                 3816
host_location                       3810
host_response_time                  3818
host_response_rate                  3295
host_acceptance_rate                3045
host_is_superhost                   3816
host_has_profile_pic                3816
host_identity_verified              3816
dtype: int64

In [181]:
#droping NAs in machine learning dataframe
ml_df = ml_df.dropna()
ml_df.count()

id                                  2651
host_id                             2651
booking_id                          2651
name                                2651
neighbourhood_group                 2651
city                                2651
state                               2651
zipcode                             2651
latitude                            2651
longitude                           2651
property_type                       2651
room_type                           2651
accommodates                        2651
bathrooms                           2651
bedrooms                            2651
beds                                2651
bed_type                            2651
instant_bookable                    2651
cancellation_policy                 2651
require_guest_profile_picture       2651
require_guest_phone_verification    2651
number_of_reviews                   2651
first_review                        2651
last_review                         2651
review_scores_rating                2651
review_scores_accuracy              2651
review_scores_cleanliness           2651
review_scores_checkin               2651
review_scores_communication         2651
review_scores_location              2651
review_scores_value                 2651
reviews_per_month                   2651
host_name                           2651
host_since                          2651
host_listings_count                 2651
host_location                       2651
host_response_time                  2651
host_response_rate                  2651
host_acceptance_rate                2651
host_is_superhost                   2651
host_has_profile_pic                2651
host_identity_verified              2651
dtype: int64

In [182]:
#defining a good or a bad rating avg rating 9.46
ml_df['rating_good_or_bad'] = np.where(ml_df['review_scores_value'] > 8.9, 'good_review', 'bad_review')

#checking good vs. bad rating count
good_bad_review_count = ml_df.groupby('rating_good_or_bad')['reviews_per_month'].count()
print(good_bad_review_count)

#ml_df.to_csv('ml_check.csv', index= False)

rating_good_or_bad
bad_review      189
good_review    2462
Name: reviews_per_month, dtype: int64

In [183]:
#removing rating info to avoid skewing ML model 
ml_final = ml_df.copy()
ml_final.reset_index(inplace=True)
ml_final

,index,id,host_id,booking_id,name,neighbourhood_group,city,state,zipcode,latitude,...,host_since,host_listings_count,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_has_profile_pic,host_identity_verified,rating_good_or_bad
0,2,3697351,18835179,1214,5 Blocks from Pike Place Market,Downtown,Seattle,WA,98121.0,47.61381379,...,2014-07-24,1.0,"Seattle, Washington, United States",within a day,0.7,1.0,False,True,False,good_review
1,3,5538874,10590193,2406,Nice Cozy Futon in Mapleleaf,Northgate,Seattle,WA,98125.0,47.70438255,...,2013-12-12,2.0,"Seattle, Washington, United States",within an hour,1,1.0,True,True,True,good_review
2,4,2071305,10590193,2420,Nice Mapleleaf Single Private Room,Northgate,Seattle,WA,98125.0,47.70437884,...,2013-12-12,2.0,"Seattle, Washington, United States",within an hour,1,1.0,True,True,True,good_review
3,5,7462439,6678025,587,"Capitol Hill Apt, Magnificent Views",Central Area,Seattle,WA,98122.0,47.61780091,...,2013-06-01,1.0,"Seattle, Washington, United States",within a few hours,1,1.0,False,True,True,bad_review
4,6,14386,39377,541,Quiet Cozy Upstairs BR Green Lake,Other neighborhoods,Seattle,WA,98103.0,47.68724568,...,2009-09-18,3.0,"Seattle, Washington, United States",within a few hours,1,1.0,False,True,False,good_review
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2646,3774,9797000,50487726,2155,"Lightrail, ethnic eateries, parks!",Rainier Valley,Seattle,WA,98118.0,47.53649713,...,2015-12-03,1.0,US,within an hour,1,1.0,False,True,False,good_review
2647,3775,9820818,50586425,2176,View Ridge Cottage on Burke-Gilman,Other neighborhoods,Seattle,WA,98115.0,47.67647014,...,2015-12-05,1.0,"Seattle, Washington, United States",within an hour,1,1.0,False,True,True,good_review
2648,3779,9863565,50763436,3633,Quiet Capitol Hill Studio,Capitol Hill,Seattle,WA,98112.0,47.62401655,...,2015-12-07,1.0,"Seattle, Washington, United States",within a few hours,1,1.0,False,True,False,good_review
2649,3780,9865846,22302229,792,Cozy Duplex Near UW,University District,Seattle,WA,98105.0,47.66713218,...,2014-10-08,1.0,"Gig Harbor, Washington, United States",within a few hours,0.95,1.0,False,True,True,good_review
2650,3787,9939359,7696606,2716,Capitol Hill Studio Apartment,Capitol Hill,Seattle,WA,98122.0,47.61669008,...,2013-07-24,1.0,"Minneapolis, Minnesota, United States",within a day,1,1.0,False,True,False,good_review

Encodes for All True and False Variables:

In [184]:
# Creates T/F encoding based on avg. number of reviews, accommodations, beds, and baths 

# number of review avg = 30
# number of accomodations avg = 3
# number of bedrooms avg = 1
# number of beds avg = 2
# number of baths avg = 1.5
# host response rate avg = 0.95
# host acceptance rate avg = .99

ml_final['num_of_reivews_gt_avg'] = np.where(ml_df['number_of_reviews'] > 30, True, False)
ml_final['num_of_accom_gt_avg'] = np.where(ml_df['accommodates'] > 3, True, False)
ml_final['num_of_bedrooms_gt_avg'] = np.where(ml_df['bedrooms'] > 1, True, False)
ml_final['num_of_beds_gt_avg'] = np.where(ml_df['beds'] > 2, True, False)
ml_final['num_of_baths_gt_avg'] = np.where(ml_df['bathrooms'] > 1.5, True, False)
ml_final['response_rate_gt_avg'] = np.where(ml_df['bathrooms'] > .95, True, False)
ml_final['accept_rate_gt_avg'] = np.where(ml_df['bathrooms'] > .99, True, False)

ml_final.head()

,index,id,host_id,booking_id,name,neighbourhood_group,city,state,zipcode,latitude,...,host_has_profile_pic,host_identity_verified,rating_good_or_bad,num_of_reivews_gt_avg,num_of_accom_gt_avg,num_of_bedrooms_gt_avg,num_of_beds_gt_avg,num_of_baths_gt_avg,response_rate_gt_avg,accept_rate_gt_avg
0,2,3697351,18835179,1214,5 Blocks from Pike Place Market,Downtown,Seattle,WA,98121.0,47.61381379,...,True,False,good_review,True,False,False,False,False,True,True
1,3,5538874,10590193,2406,Nice Cozy Futon in Mapleleaf,Northgate,Seattle,WA,98125.0,47.70438255,...,True,True,good_review,False,False,False,False,False,True,True
2,4,2071305,10590193,2420,Nice Mapleleaf Single Private Room,Northgate,Seattle,WA,98125.0,47.70437884,...,True,True,good_review,False,False,False,False,False,True,True
3,5,7462439,6678025,587,"Capitol Hill Apt, Magnificent Views",Central Area,Seattle,WA,98122.0,47.61780091,...,True,True,bad_review,False,False,False,False,False,True,True
4,6,14386,39377,541,Quiet Cozy Upstairs BR Green Lake,Other neighborhoods,Seattle,WA,98103.0,47.68724568,...,True,False,good_review,False,False,False,False,False,True,True

In [185]:
##encoding for acceptance rate

# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# encoding values
enc_df = pd.DataFrame(enc.fit_transform(ml_final[['accept_rate_gt_avg']]).toarray())
# joining with database
ml_final= ml_final.join(enc_df)
ml_final.rename(columns = {0:'accept_rate_below_avg', 1:'accept_rate_above_avg'}, inplace = True)
ml_final.tail()

,index,id,host_id,booking_id,name,neighbourhood_group,city,state,zipcode,latitude,...,rating_good_or_bad,num_of_reivews_gt_avg,num_of_accom_gt_avg,num_of_bedrooms_gt_avg,num_of_beds_gt_avg,num_of_baths_gt_avg,response_rate_gt_avg,accept_rate_gt_avg,accept_rate_below_avg,accept_rate_above_avg
2646,3774,9797000,50487726,2155,"Lightrail, ethnic eateries, parks!",Rainier Valley,Seattle,WA,98118.0,47.53649713,...,good_review,False,True,False,False,False,True,True,0.0,1.0
2647,3775,9820818,50586425,2176,View Ridge Cottage on Burke-Gilman,Other neighborhoods,Seattle,WA,98115.0,47.67647014,...,good_review,False,True,True,True,False,True,True,0.0,1.0
2648,3779,9863565,50763436,3633,Quiet Capitol Hill Studio,Capitol Hill,Seattle,WA,98112.0,47.62401655,...,good_review,False,False,False,False,False,True,True,0.0,1.0
2649,3780,9865846,22302229,792,Cozy Duplex Near UW,University District,Seattle,WA,98105.0,47.66713218,...,good_review,False,True,True,False,False,True,True,0.0,1.0
2650,3787,9939359,7696606,2716,Capitol Hill Studio Apartment,Capitol Hill,Seattle,WA,98122.0,47.61669008,...,good_review,False,False,False,False,False,True,True,0.0,1.0

In [186]:
##encoding for num or reviews

# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# encoding values
enc_df = pd.DataFrame(enc.fit_transform(ml_final[['response_rate_gt_avg']]).toarray())
# joining with database
ml_final= ml_final.join(enc_df)
ml_final.rename(columns = {0:'response_rate_below_avg', 1:'response_rate_above_avg'}, inplace = True)
ml_final.tail()

,index,id,host_id,booking_id,name,neighbourhood_group,city,state,zipcode,latitude,...,num_of_accom_gt_avg,num_of_bedrooms_gt_avg,num_of_beds_gt_avg,num_of_baths_gt_avg,response_rate_gt_avg,accept_rate_gt_avg,accept_rate_below_avg,accept_rate_above_avg,response_rate_below_avg,response_rate_above_avg
2646,3774,9797000,50487726,2155,"Lightrail, ethnic eateries, parks!",Rainier Valley,Seattle,WA,98118.0,47.53649713,...,True,False,False,False,True,True,0.0,1.0,0.0,1.0
2647,3775,9820818,50586425,2176,View Ridge Cottage on Burke-Gilman,Other neighborhoods,Seattle,WA,98115.0,47.67647014,...,True,True,True,False,True,True,0.0,1.0,0.0,1.0
2648,3779,9863565,50763436,3633,Quiet Capitol Hill Studio,Capitol Hill,Seattle,WA,98112.0,47.62401655,...,False,False,False,False,True,True,0.0,1.0,0.0,1.0
2649,3780,9865846,22302229,792,Cozy Duplex Near UW,University District,Seattle,WA,98105.0,47.66713218,...,True,True,False,False,True,True,0.0,1.0,0.0,1.0
2650,3787,9939359,7696606,2716,Capitol Hill Studio Apartment,Capitol Hill,Seattle,WA,98122.0,47.61669008,...,False,False,False,False,True,True,0.0,1.0,0.0,1.0

In [187]:
##encoding for num or reviews

# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# encoding values
enc_df = pd.DataFrame(enc.fit_transform(ml_final[['num_of_reivews_gt_avg']]).toarray())
# joining with database
ml_final= ml_final.join(enc_df)
ml_final.rename(columns = {0:'below_avg_num_of_reviews', 1:'above_avg_num_of_reviews'}, inplace = True)
ml_final.tail()

,index,id,host_id,booking_id,name,neighbourhood_group,city,state,zipcode,latitude,...,num_of_beds_gt_avg,num_of_baths_gt_avg,response_rate_gt_avg,accept_rate_gt_avg,accept_rate_below_avg,accept_rate_above_avg,response_rate_below_avg,response_rate_above_avg,below_avg_num_of_reviews,above_avg_num_of_reviews
2646,3774,9797000,50487726,2155,"Lightrail, ethnic eateries, parks!",Rainier Valley,Seattle,WA,98118.0,47.53649713,...,False,False,True,True,0.0,1.0,0.0,1.0,1.0,0.0
2647,3775,9820818,50586425,2176,View Ridge Cottage on Burke-Gilman,Other neighborhoods,Seattle,WA,98115.0,47.67647014,...,True,False,True,True,0.0,1.0,0.0,1.0,1.0,0.0
2648,3779,9863565,50763436,3633,Quiet Capitol Hill Studio,Capitol Hill,Seattle,WA,98112.0,47.62401655,...,False,False,True,True,0.0,1.0,0.0,1.0,1.0,0.0
2649,3780,9865846,22302229,792,Cozy Duplex Near UW,University District,Seattle,WA,98105.0,47.66713218,...,False,False,True,True,0.0,1.0,0.0,1.0,1.0,0.0
2650,3787,9939359,7696606,2716,Capitol Hill Studio Apartment,Capitol Hill,Seattle,WA,98122.0,47.61669008,...,False,False,True,True,0.0,1.0,0.0,1.0,1.0,0.0

In [188]:
##encoding for num of accomodations 

# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# encoding values
enc_df = pd.DataFrame(enc.fit_transform(ml_final[['num_of_accom_gt_avg']]).toarray())
# joining with database
ml_final= ml_final.join(enc_df)
ml_final.rename(columns = {0:'below_avg_num_of_accom', 1:'above_avg_num_of_accom'}, inplace = True)
ml_final.tail()

,index,id,host_id,booking_id,name,neighbourhood_group,city,state,zipcode,latitude,...,response_rate_gt_avg,accept_rate_gt_avg,accept_rate_below_avg,accept_rate_above_avg,response_rate_below_avg,response_rate_above_avg,below_avg_num_of_reviews,above_avg_num_of_reviews,below_avg_num_of_accom,above_avg_num_of_accom
2646,3774,9797000,50487726,2155,"Lightrail, ethnic eateries, parks!",Rainier Valley,Seattle,WA,98118.0,47.53649713,...,True,True,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
2647,3775,9820818,50586425,2176,View Ridge Cottage on Burke-Gilman,Other neighborhoods,Seattle,WA,98115.0,47.67647014,...,True,True,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
2648,3779,9863565,50763436,3633,Quiet Capitol Hill Studio,Capitol Hill,Seattle,WA,98112.0,47.62401655,...,True,True,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
2649,3780,9865846,22302229,792,Cozy Duplex Near UW,University District,Seattle,WA,98105.0,47.66713218,...,True,True,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
2650,3787,9939359,7696606,2716,Capitol Hill Studio Apartment,Capitol Hill,Seattle,WA,98122.0,47.61669008,...,True,True,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0

In [189]:
##encoding for num of bedrooms

# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# encoding values
enc_df = pd.DataFrame(enc.fit_transform(ml_final[['num_of_bedrooms_gt_avg']]).toarray())
# joining with database
ml_final= ml_final.join(enc_df)
ml_final.rename(columns = {0:'below_avg_num_of_bedrooms', 1:'above_avg_num_of_bedrooms'}, inplace = True)
ml_final.tail()

,index,id,host_id,booking_id,name,neighbourhood_group,city,state,zipcode,latitude,...,accept_rate_below_avg,accept_rate_above_avg,response_rate_below_avg,response_rate_above_avg,below_avg_num_of_reviews,above_avg_num_of_reviews,below_avg_num_of_accom,above_avg_num_of_accom,below_avg_num_of_bedrooms,above_avg_num_of_bedrooms
2646,3774,9797000,50487726,2155,"Lightrail, ethnic eateries, parks!",Rainier Valley,Seattle,WA,98118.0,47.53649713,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0
2647,3775,9820818,50586425,2176,View Ridge Cottage on Burke-Gilman,Other neighborhoods,Seattle,WA,98115.0,47.67647014,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0
2648,3779,9863565,50763436,3633,Quiet Capitol Hill Studio,Capitol Hill,Seattle,WA,98112.0,47.62401655,...,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
2649,3780,9865846,22302229,792,Cozy Duplex Near UW,University District,Seattle,WA,98105.0,47.66713218,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0
2650,3787,9939359,7696606,2716,Capitol Hill Studio Apartment,Capitol Hill,Seattle,WA,98122.0,47.61669008,...,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0

In [190]:
##encoding for num of beds

# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# encoding values
enc_df = pd.DataFrame(enc.fit_transform(ml_final[['num_of_beds_gt_avg']]).toarray())
# joining with database
ml_final= ml_final.join(enc_df)
ml_final.rename(columns = {0:'below_avg_num_of_beds', 1:'above_avg_num_of_beds'}, inplace = True)
ml_final.tail()

,index,id,host_id,booking_id,name,neighbourhood_group,city,state,zipcode,latitude,...,response_rate_below_avg,response_rate_above_avg,below_avg_num_of_reviews,above_avg_num_of_reviews,below_avg_num_of_accom,above_avg_num_of_accom,below_avg_num_of_bedrooms,above_avg_num_of_bedrooms,below_avg_num_of_beds,above_avg_num_of_beds
2646,3774,9797000,50487726,2155,"Lightrail, ethnic eateries, parks!",Rainier Valley,Seattle,WA,98118.0,47.53649713,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
2647,3775,9820818,50586425,2176,View Ridge Cottage on Burke-Gilman,Other neighborhoods,Seattle,WA,98115.0,47.67647014,...,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
2648,3779,9863565,50763436,3633,Quiet Capitol Hill Studio,Capitol Hill,Seattle,WA,98112.0,47.62401655,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
2649,3780,9865846,22302229,792,Cozy Duplex Near UW,University District,Seattle,WA,98105.0,47.66713218,...,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2650,3787,9939359,7696606,2716,Capitol Hill Studio Apartment,Capitol Hill,Seattle,WA,98122.0,47.61669008,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [191]:
##encoding for num of baths

# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# encoding values
enc_df = pd.DataFrame(enc.fit_transform(ml_final[['num_of_baths_gt_avg']]).toarray())
# joining with database
ml_final= ml_final.join(enc_df)
ml_final.rename(columns = {0:'below_avg_num_of_baths', 1:'above_avg_num_of_baths'}, inplace = True)
ml_final.tail()

,index,id,host_id,booking_id,name,neighbourhood_group,city,state,zipcode,latitude,...,below_avg_num_of_reviews,above_avg_num_of_reviews,below_avg_num_of_accom,above_avg_num_of_accom,below_avg_num_of_bedrooms,above_avg_num_of_bedrooms,below_avg_num_of_beds,above_avg_num_of_beds,below_avg_num_of_baths,above_avg_num_of_baths
2646,3774,9797000,50487726,2155,"Lightrail, ethnic eateries, parks!",Rainier Valley,Seattle,WA,98118.0,47.53649713,...,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
2647,3775,9820818,50586425,2176,View Ridge Cottage on Burke-Gilman,Other neighborhoods,Seattle,WA,98115.0,47.67647014,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
2648,3779,9863565,50763436,3633,Quiet Capitol Hill Studio,Capitol Hill,Seattle,WA,98112.0,47.62401655,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
2649,3780,9865846,22302229,792,Cozy Duplex Near UW,University District,Seattle,WA,98105.0,47.66713218,...,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
2650,3787,9939359,7696606,2716,Capitol Hill Studio Apartment,Capitol Hill,Seattle,WA,98122.0,47.61669008,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [192]:


##encoding for superhost

# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# encoding values
enc_df = pd.DataFrame(enc.fit_transform(ml_final[['host_is_superhost']]).toarray())
# joining with database
ml_final= ml_final.join(enc_df)
ml_final.rename(columns = {0:'not_a_superhost', 1:'a_superhost'}, inplace = True)
ml_final.tail()

,index,id,host_id,booking_id,name,neighbourhood_group,city,state,zipcode,latitude,...,below_avg_num_of_accom,above_avg_num_of_accom,below_avg_num_of_bedrooms,above_avg_num_of_bedrooms,below_avg_num_of_beds,above_avg_num_of_beds,below_avg_num_of_baths,above_avg_num_of_baths,not_a_superhost,a_superhost
2646,3774,9797000,50487726,2155,"Lightrail, ethnic eateries, parks!",Rainier Valley,Seattle,WA,98118.0,47.53649713,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
2647,3775,9820818,50586425,2176,View Ridge Cottage on Burke-Gilman,Other neighborhoods,Seattle,WA,98115.0,47.67647014,...,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
2648,3779,9863565,50763436,3633,Quiet Capitol Hill Studio,Capitol Hill,Seattle,WA,98112.0,47.62401655,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
2649,3780,9865846,22302229,792,Cozy Duplex Near UW,University District,Seattle,WA,98105.0,47.66713218,...,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
2650,3787,9939359,7696606,2716,Capitol Hill Studio Apartment,Capitol Hill,Seattle,WA,98122.0,47.61669008,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [193]:
##encoding for host has profile pic

# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# encoding values
enc_df = pd.DataFrame(enc.fit_transform(ml_final[['host_has_profile_pic']]).toarray())
# joining with database
ml_final= ml_final.join(enc_df)
ml_final.rename(columns = {0:'host_does_not_have_profile_pic', 1:'host_does_have_profile_pic'}, inplace = True)
ml_final.head()

,index,id,host_id,booking_id,name,neighbourhood_group,city,state,zipcode,latitude,...,below_avg_num_of_bedrooms,above_avg_num_of_bedrooms,below_avg_num_of_beds,above_avg_num_of_beds,below_avg_num_of_baths,above_avg_num_of_baths,not_a_superhost,a_superhost,host_does_not_have_profile_pic,host_does_have_profile_pic
0,2,3697351,18835179,1214,5 Blocks from Pike Place Market,Downtown,Seattle,WA,98121.0,47.61381379,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
1,3,5538874,10590193,2406,Nice Cozy Futon in Mapleleaf,Northgate,Seattle,WA,98125.0,47.70438255,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
2,4,2071305,10590193,2420,Nice Mapleleaf Single Private Room,Northgate,Seattle,WA,98125.0,47.70437884,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
3,5,7462439,6678025,587,"Capitol Hill Apt, Magnificent Views",Central Area,Seattle,WA,98122.0,47.61780091,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
4,6,14386,39377,541,Quiet Cozy Upstairs BR Green Lake,Other neighborhoods,Seattle,WA,98103.0,47.68724568,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0

In [194]:
##encoding for host has identity verification 

# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# encoding values
enc_df = pd.DataFrame(enc.fit_transform(ml_final[['host_identity_verified']]).toarray())
# joining with database
ml_final= ml_final.join(enc_df)
ml_final.rename(columns = {0:'host_does_not_have_identity_ver', 1:'host_does_have_identity_ver'}, inplace = True)
ml_final.head()

,index,id,host_id,booking_id,name,neighbourhood_group,city,state,zipcode,latitude,...,below_avg_num_of_beds,above_avg_num_of_beds,below_avg_num_of_baths,above_avg_num_of_baths,not_a_superhost,a_superhost,host_does_not_have_profile_pic,host_does_have_profile_pic,host_does_not_have_identity_ver,host_does_have_identity_ver
0,2,3697351,18835179,1214,5 Blocks from Pike Place Market,Downtown,Seattle,WA,98121.0,47.61381379,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
1,3,5538874,10590193,2406,Nice Cozy Futon in Mapleleaf,Northgate,Seattle,WA,98125.0,47.70438255,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
2,4,2071305,10590193,2420,Nice Mapleleaf Single Private Room,Northgate,Seattle,WA,98125.0,47.70437884,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
3,5,7462439,6678025,587,"Capitol Hill Apt, Magnificent Views",Central Area,Seattle,WA,98122.0,47.61780091,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
4,6,14386,39377,541,Quiet Cozy Upstairs BR Green Lake,Other neighborhoods,Seattle,WA,98103.0,47.68724568,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0

In [195]:
# ##encoding for host requires a license 

# # creating instance of one-hot-encoder
# enc = OneHotEncoder(handle_unknown='ignore')
# # encoding values
# enc_df = pd.DataFrame(enc.fit_transform(ml_final[['requires_license']]).toarray())
# # joining with database
# ml_final= ml_final.join(enc_df)
# ml_final.rename(columns = {0:'host_does_not_require_license', 1:'host_does_require_license'}, inplace = True)
# ml_final.head()

In [196]:
##encoding for instant_bookability 

# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# encoding values
enc_df = pd.DataFrame(enc.fit_transform(ml_final[['instant_bookable']]).toarray())
# joining with database
ml_final= ml_final.join(enc_df)
ml_final.rename(columns = {0:'not_instantly_bookable', 1:'instantly_bookable'}, inplace = True)
ml_final.head()

,index,id,host_id,booking_id,name,neighbourhood_group,city,state,zipcode,latitude,...,below_avg_num_of_baths,above_avg_num_of_baths,not_a_superhost,a_superhost,host_does_not_have_profile_pic,host_does_have_profile_pic,host_does_not_have_identity_ver,host_does_have_identity_ver,not_instantly_bookable,instantly_bookable
0,2,3697351,18835179,1214,5 Blocks from Pike Place Market,Downtown,Seattle,WA,98121.0,47.61381379,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
1,3,5538874,10590193,2406,Nice Cozy Futon in Mapleleaf,Northgate,Seattle,WA,98125.0,47.70438255,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
2,4,2071305,10590193,2420,Nice Mapleleaf Single Private Room,Northgate,Seattle,WA,98125.0,47.70437884,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0
3,5,7462439,6678025,587,"Capitol Hill Apt, Magnificent Views",Central Area,Seattle,WA,98122.0,47.61780091,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
4,6,14386,39377,541,Quiet Cozy Upstairs BR Green Lake,Other neighborhoods,Seattle,WA,98103.0,47.68724568,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0

In [197]:
##encoding for requires guest profile picture 

# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# encoding values
enc_df = pd.DataFrame(enc.fit_transform(ml_final[['require_guest_profile_picture']]).toarray())
# joining with database
ml_final= ml_final.join(enc_df)
ml_final.rename(columns = {0:'does_not_require_guest_prof_pic', 1:'requires_guest_profile_pic'}, inplace = True)
ml_final.head()

,index,id,host_id,booking_id,name,neighbourhood_group,city,state,zipcode,latitude,...,not_a_superhost,a_superhost,host_does_not_have_profile_pic,host_does_have_profile_pic,host_does_not_have_identity_ver,host_does_have_identity_ver,not_instantly_bookable,instantly_bookable,does_not_require_guest_prof_pic,requires_guest_profile_pic
0,2,3697351,18835179,1214,5 Blocks from Pike Place Market,Downtown,Seattle,WA,98121.0,47.61381379,...,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
1,3,5538874,10590193,2406,Nice Cozy Futon in Mapleleaf,Northgate,Seattle,WA,98125.0,47.70438255,...,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
2,4,2071305,10590193,2420,Nice Mapleleaf Single Private Room,Northgate,Seattle,WA,98125.0,47.70437884,...,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
3,5,7462439,6678025,587,"Capitol Hill Apt, Magnificent Views",Central Area,Seattle,WA,98122.0,47.61780091,...,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
4,6,14386,39377,541,Quiet Cozy Upstairs BR Green Lake,Other neighborhoods,Seattle,WA,98103.0,47.68724568,...,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0

In [198]:
##encoding for requires guest phone verification 

# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# encoding values
enc_df = pd.DataFrame(enc.fit_transform(ml_final[['require_guest_phone_verification']]).toarray())
# joining with database
ml_final= ml_final.join(enc_df)
ml_final.rename(columns = {0:'does_not_require_guest_phone_verification', 1:'requires_guest_phone_verification'}, inplace = True)
ml_final.tail()

,index,id,host_id,booking_id,name,neighbourhood_group,city,state,zipcode,latitude,...,host_does_not_have_profile_pic,host_does_have_profile_pic,host_does_not_have_identity_ver,host_does_have_identity_ver,not_instantly_bookable,instantly_bookable,does_not_require_guest_prof_pic,requires_guest_profile_pic,does_not_require_guest_phone_verification,requires_guest_phone_verification
2646,3774,9797000,50487726,2155,"Lightrail, ethnic eateries, parks!",Rainier Valley,Seattle,WA,98118.0,47.53649713,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
2647,3775,9820818,50586425,2176,View Ridge Cottage on Burke-Gilman,Other neighborhoods,Seattle,WA,98115.0,47.67647014,...,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
2648,3779,9863565,50763436,3633,Quiet Capitol Hill Studio,Capitol Hill,Seattle,WA,98112.0,47.62401655,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
2649,3780,9865846,22302229,792,Cozy Duplex Near UW,University District,Seattle,WA,98105.0,47.66713218,...,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
2650,3787,9939359,7696606,2716,Capitol Hill Studio Apartment,Capitol Hill,Seattle,WA,98122.0,47.61669008,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

Encodes for All Dynamic Variables:

In [199]:
##encoding for host response time 

# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# encoding values
enc_df = pd.DataFrame(enc.fit_transform(ml_final[['host_response_time']]).toarray())
# joining with database
ml_final= ml_final.join(enc_df)
ml_final.rename(columns = {0:'rt_few_days', 1:'rt_within_day', 2:'rt_few_hours', 3:'rt_within_hours',}, inplace = True)
ml_final.head()
#ml_final.to_csv('test.csv')

,index,id,host_id,booking_id,name,neighbourhood_group,city,state,zipcode,latitude,...,not_instantly_bookable,instantly_bookable,does_not_require_guest_prof_pic,requires_guest_profile_pic,does_not_require_guest_phone_verification,requires_guest_phone_verification,rt_few_days,rt_within_day,rt_few_hours,rt_within_hours
0,2,3697351,18835179,1214,5 Blocks from Pike Place Market,Downtown,Seattle,WA,98121.0,47.61381379,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,3,5538874,10590193,2406,Nice Cozy Futon in Mapleleaf,Northgate,Seattle,WA,98125.0,47.70438255,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,4,2071305,10590193,2420,Nice Mapleleaf Single Private Room,Northgate,Seattle,WA,98125.0,47.70437884,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,5,7462439,6678025,587,"Capitol Hill Apt, Magnificent Views",Central Area,Seattle,WA,98122.0,47.61780091,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,6,14386,39377,541,Quiet Cozy Upstairs BR Green Lake,Other neighborhoods,Seattle,WA,98103.0,47.68724568,...,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [200]:
##encoding for neighbourhood

# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# encoding values
enc_df = pd.DataFrame(enc.fit_transform(ml_final[['neighbourhood_group']]).toarray())
# joining with database
ml_final= ml_final.join(enc_df)
ml_final.rename(columns = {0:'location_ballard', 1:'location_beacon_hill', 2:'location_capital_hill', 3:'location_cascade', 4:'location_central_area', 5:'location_delridge', 6:'location_downtown',
  7:'location_interbay', 8:'location_lake_city', 9:'location_magnolia', 10:'location_northgate', 11:'location_other', 12:'location_queen_anne', 13:'location_rainier_vally', 14:'location_seward_park', 15:'location_university_district', 16:'location_west_seattle'}, inplace = True)
ml_final.head()
#ml_final.to_csv('test.csv')

,index,id,host_id,booking_id,name,neighbourhood_group,city,state,zipcode,latitude,...,location_interbay,location_lake_city,location_magnolia,location_northgate,location_other,location_queen_anne,location_rainier_vally,location_seward_park,location_university_district,location_west_seattle
0,2,3697351,18835179,1214,5 Blocks from Pike Place Market,Downtown,Seattle,WA,98121.0,47.61381379,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,3,5538874,10590193,2406,Nice Cozy Futon in Mapleleaf,Northgate,Seattle,WA,98125.0,47.70438255,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4,2071305,10590193,2420,Nice Mapleleaf Single Private Room,Northgate,Seattle,WA,98125.0,47.70437884,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,5,7462439,6678025,587,"Capitol Hill Apt, Magnificent Views",Central Area,Seattle,WA,98122.0,47.61780091,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,6,14386,39377,541,Quiet Cozy Upstairs BR Green Lake,Other neighborhoods,Seattle,WA,98103.0,47.68724568,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [201]:
##encoding for property type 

# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# encoding values
enc_df = pd.DataFrame(enc.fit_transform(ml_final[['property_type']]).toarray())
# joining with database
ml_final= ml_final.join(enc_df)
ml_final.rename(columns = {0:'pt_apartment', 1:'pt_b&b', 2:'pt_boat', 3:'pt_bungalow', 4:'pt_cabin', 5:'pt_rv', 6:'pt_chalet',
  7:'pt_condo', 8:'pt_dorm', 9:'pt_house', 10:'pt_loft', 11:'pt_other', 12:'pt_tent', 13:'pt_townhouse', 14:'pt_treehouse', 15: 'pt_yurt'}, inplace= True)

ml_final.head()

,index,id,host_id,booking_id,name,neighbourhood_group,city,state,zipcode,latitude,...,pt_chalet,pt_condo,pt_dorm,pt_house,pt_loft,pt_other,pt_tent,pt_townhouse,pt_treehouse,pt_yurt
0,2,3697351,18835179,1214,5 Blocks from Pike Place Market,Downtown,Seattle,WA,98121.0,47.61381379,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,3,5538874,10590193,2406,Nice Cozy Futon in Mapleleaf,Northgate,Seattle,WA,98125.0,47.70438255,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4,2071305,10590193,2420,Nice Mapleleaf Single Private Room,Northgate,Seattle,WA,98125.0,47.70437884,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,5,7462439,6678025,587,"Capitol Hill Apt, Magnificent Views",Central Area,Seattle,WA,98122.0,47.61780091,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,6,14386,39377,541,Quiet Cozy Upstairs BR Green Lake,Other neighborhoods,Seattle,WA,98103.0,47.68724568,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [202]:
##encoding for room type

# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# encoding values
enc_df = pd.DataFrame(enc.fit_transform(ml_final[['room_type']]).toarray())
# joining with database
ml_final= ml_final.join(enc_df)
ml_final.rename(columns = {0:'rt_entire_home', 1:'rt_private_room', 2:'rt_shared_room'}, inplace= True)

ml_final.head()

,index,id,host_id,booking_id,name,neighbourhood_group,city,state,zipcode,latitude,...,pt_house,pt_loft,pt_other,pt_tent,pt_townhouse,pt_treehouse,pt_yurt,rt_entire_home,rt_private_room,rt_shared_room
0,2,3697351,18835179,1214,5 Blocks from Pike Place Market,Downtown,Seattle,WA,98121.0,47.61381379,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,3,5538874,10590193,2406,Nice Cozy Futon in Mapleleaf,Northgate,Seattle,WA,98125.0,47.70438255,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,4,2071305,10590193,2420,Nice Mapleleaf Single Private Room,Northgate,Seattle,WA,98125.0,47.70437884,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,5,7462439,6678025,587,"Capitol Hill Apt, Magnificent Views",Central Area,Seattle,WA,98122.0,47.61780091,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,6,14386,39377,541,Quiet Cozy Upstairs BR Green Lake,Other neighborhoods,Seattle,WA,98103.0,47.68724568,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [203]:
##encoding for bed type

# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# encoding values
enc_df = pd.DataFrame(enc.fit_transform(ml_final[['bed_type']]).toarray())
# joining with database
ml_final= ml_final.join(enc_df)
ml_final.rename(columns = {0:'bt_air_bed', 1:'bt_couch', 2:'bt_futon', 3:'bt_pull_out_sofa',4:'bt_real_bed'}, inplace= True)

ml_final.head()

,index,id,host_id,booking_id,name,neighbourhood_group,city,state,zipcode,latitude,...,pt_treehouse,pt_yurt,rt_entire_home,rt_private_room,rt_shared_room,bt_air_bed,bt_couch,bt_futon,bt_pull_out_sofa,bt_real_bed
0,2,3697351,18835179,1214,5 Blocks from Pike Place Market,Downtown,Seattle,WA,98121.0,47.61381379,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,3,5538874,10590193,2406,Nice Cozy Futon in Mapleleaf,Northgate,Seattle,WA,98125.0,47.70438255,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,4,2071305,10590193,2420,Nice Mapleleaf Single Private Room,Northgate,Seattle,WA,98125.0,47.70437884,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
3,5,7462439,6678025,587,"Capitol Hill Apt, Magnificent Views",Central Area,Seattle,WA,98122.0,47.61780091,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
4,6,14386,39377,541,Quiet Cozy Upstairs BR Green Lake,Other neighborhoods,Seattle,WA,98103.0,47.68724568,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0

In [204]:
##encoding for cancellation policy 

# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# encoding values
enc_df = pd.DataFrame(enc.fit_transform(ml_final[['cancellation_policy']]).toarray())
# joining with database
ml_final= ml_final.join(enc_df)
ml_final.rename(columns = {0:'cp_flexible', 1:'cp_moderate', 2:'cp_strict'}, inplace= True)

ml_final.head()

,index,id,host_id,booking_id,name,neighbourhood_group,city,state,zipcode,latitude,...,rt_private_room,rt_shared_room,bt_air_bed,bt_couch,bt_futon,bt_pull_out_sofa,bt_real_bed,cp_flexible,cp_moderate,cp_strict
0,2,3697351,18835179,1214,5 Blocks from Pike Place Market,Downtown,Seattle,WA,98121.0,47.61381379,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,3,5538874,10590193,2406,Nice Cozy Futon in Mapleleaf,Northgate,Seattle,WA,98125.0,47.70438255,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,4,2071305,10590193,2420,Nice Mapleleaf Single Private Room,Northgate,Seattle,WA,98125.0,47.70437884,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,5,7462439,6678025,587,"Capitol Hill Apt, Magnificent Views",Central Area,Seattle,WA,98122.0,47.61780091,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,6,14386,39377,541,Quiet Cozy Upstairs BR Green Lake,Other neighborhoods,Seattle,WA,98103.0,47.68724568,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [205]:
ml_final =ml_final.drop('index', axis=1)
ml_final.count()

id                     2651
host_id                2651
booking_id             2651
name                   2651
neighbourhood_group    2651
                       ...
bt_pull_out_sofa       2651
bt_real_bed            2651
cp_flexible            2651
cp_moderate            2651
cp_strict              2651
Length: 124, dtype: int64

In [206]:

ml_final.to_csv('ml_final_data.csv', index= False)